main: mainp4.o insert.o print.o search.o high.o balance.o delete.o free.o BFS.o 
	gcc -o main mainp4.o insert.o print.o search.o high.o balance.o delete.o free.o BFS.o 
clean:
	rm main mainp4.o insert.o print.o search.o high.o balance.o delete.o free.o BFS.o
