main: mainp2.o print.o init.o add.o search.o delete.o
	gcc -o main mainp2.o print.o init.o add.o search.o delete.o
mainp2.o: mainp2.c
	gcc -c mainp2.c
print.o: print.c
	gcc -c print.c
init.o: init.c
	gcc -c init.c
add.o: add.c
	gcc -c add.c
search.o: search.c
	gcc -c search.c
delete.o: delete.c
	gcc -c delete.c
